/**
 * Chatbot 家族文案集中层
 *
 * 本批不接 useLocale：locale-packs 守卫要求 7 个语言包键位完全一致，
 * 只给部分包加 chat 键会让未覆盖语言在运行时退回 t() 的路径字符串。
 * 因此所有中文文案收在这一个文件里，后续 i18n 批只需改此文件 + 补 7 个语言包，
 * 不必逐个组件返工。带参文案用函数表达，避免调用侧拼字符串。
 */
export const chatLabels = {
  sender: {
    placeholder: '输入消息...',
    sendOnEnterPlaceholder: '输入消息，按 Enter 发送，Shift+Enter 换行',
    attach: '添加附件',
    dropHint: '松开以上传文件',
    send: '发送',
    stop: '停止生成',
  },
  list: {
    label: '对话消息',
    empty: '暂无对话消息',
    backToBottom: '回到对话底部',
  },
  message: {
    error: '消息发送失败',
    cancelled: '已停止生成',
    edited: '已编辑',
    duration: (text) => `（用时 ${text}）`,
    user: '我',
    assistant: 'AI助手',
    tip: '内容由 AI 生成，仅供参考',
  },
  thinking: {
    pending: '思考中...',
    done: '已深度思考',
    placeholder: '正在思考中...',
  },
  actionbar: {
    group: '消息动作',
    copy: '复制',
    copied: '已复制',
    regenerate: '重新生成',
    edit: '编辑',
  },
  attachments: {
    done: '已上传',
    failed: '上传失败',
    remove: (name) => (name ? `移除附件 ${name}` : '移除附件'),
  },
  markdown: {
    copyCode: '复制代码',
    copied: '已复制',
    citation: (num) => `查看第 ${num} 条来源`,
    footnote: (num) => `查看第 ${num} 条脚注`,
    renderDiagram: '渲染图表',
    diagramFailed: '图表渲染失败',
  },
  sources: {
    toggle: (n) => `${n} 个来源`,
    open: '展开来源列表',
    close: '收起来源列表',
  },
  suggestion: {
    group: '推荐追问',
  },
  plan: {
    group: '执行计划',
    progress: (done, total) => `${done}/${total} 完成`,
    empty: '暂无步骤',
    expand: '展开计划',
    collapse: '收起计划',
    status: {
      pending: '等待',
      running: '执行中',
      done: '完成',
      error: '失败',
      skipped: '跳过',
    },
  },
  confirmation: {
    group: '待确认',
    title: '需要你确认',
    status: {
      pending: '等待确认',
      approved: '已批准',
      rejected: '已拒绝',
      expired: '已超时',
    },
    responded: (label) => `已选择「${label}」`,
    hint: '确认后由你的代码执行相应动作',
  },
  artifact: {
    group: '产物',
    open: '查看',
    copy: '复制内容',
    copied: '已复制',
    download: '下载',
    unknownType: '文件',
  },
  diff: {
    group: '代码改动',
    untitled: '未命名文件',
    copy: '复制 diff',
    copied: '已复制',
  },
  terminal: {
    group: '命令输出',
    copy: '复制输出',
    copied: '已复制',
    expand: '展开输出',
    collapse: '收起输出',
    empty: '（无输出）',
    truncated: (n) => `已省略 ${n} 行`,
  },
  fileTree: {
    group: '文件',
    empty: '没有文件',
    added: '新增',
    modified: '修改',
    deleted: '删除',
    renamed: '重命名',
  },
  share: {
    title: '分享会话',
    intro: '创建一个链接，让别人查看这次会话。链接的生成与权限校验由你的服务端负责。',
    linkLead: '链接已创建，拿到的人即可按下面的范围查看。',
    linkLabel: '分享链接',
    copy: '复制链接',
    copied: '已复制',
    scopeLabel: '可见范围',
    expiryLabel: '有效期',
    never: '永久有效',
    revokeHint: '撤销后该链接立即失效，已经打开过的页面也不再更新。',
    create: '创建链接',
    creating: '创建中…',
    cancel: '取消',
    close: '完成',
    revoke: '撤销链接',
    scopeAnyone: '任何人可查看',
    scopeAnyoneDesc: '拿到链接即可打开，不需要登录',
    scopeOrg: '仅本组织',
    scopeOrgDesc: '需要登录且属于同一组织',
    scopeInvited: '仅受邀成员',
    scopeInvitedDesc: '需要在成员名单内',
    expiry7: '7 天',
    expiry30: '30 天',
    expiryNever: '永久',
  },
  queue: {
    group: '待发送',
    lead: (n) => `生成中，${n} 条排队等待发送`,
    attachmentOnly: '（仅附件）',
    remove: '移出队列',
    clear: '全部清空',
  },
  speech: {
    speak: '朗读这条回复',
    stopSpeak: '停止朗读',
    startListening: '开始语音输入',
    stopListening: '停止语音输入',
  },
  widget: {
    expand: '打开助手',
    collapse: '收起助手',
    close: '关闭',
    agree: '同意并开始',
  },
  threads: {
    group: '会话列表',
    untitled: '新会话',
    newThread: '新建会话',
    searchPlaceholder: '搜索会话',
    empty: '还没有会话',
    noResult: '没有匹配的会话',
    today: '今天',
    yesterday: '昨天',
    last7: '近 7 天',
    earlier: '更早',
    pinned: '已置顶',
    archived: '已归档',
    showArchived: '显示已归档',
    hideArchived: '隐藏已归档',
    renamed: '重命名',
    more: '更多操作',
    remove: '删除会话',
    pin: '置顶',
    unpin: '取消置顶',
    archive: '归档',
    unarchive: '取消归档',
    renamePlaceholder: '会话名称',
    streaming: '生成中',
    removeConfirm: '确定删除这个会话？',
  },
  tool: {
    pending: '等待执行',
    running: '执行中',
    done: '已完成',
    error: '执行失败',
    fallback: '工具调用',
    group: (n) => `执行了 ${n} 个步骤`,
    args: '参数',
    result: '结果',
    retry: '重试',
  },
  feedback: {
    group: '回答评价',
    up: '有帮助',
    down: '没帮助',
    title: '感谢反馈',
    downTitle: '请告诉我们哪里不对',
    notePlaceholder: '补充说明（可选）',
    submit: '提交',
    cancel: '取消',
    skip: '跳过',
    reasons: ['没有理解问题', '回答不准确', '信息过时', '格式或排版混乱', '太长或太短', '有害或不当内容'],
  },
  engine: {
    sendFailed: '发送失败',
  },
  edit: {
    save: '发送',
    cancel: '取消',
    placeholder: '编辑消息后重新发送',
  },
}
