export { mount } from '@vue/test-utils'
export { describe, it, expect, vi, beforeEach } from 'vitest'

// 从包内再导出 vue 常用 API，测试文件统一从 helpers 引入
export {
  defineComponent,
  h,
  ref,
  computed,
  nextTick,
} from 'vue'

// 根 vitest 配置通过 server.deps.inline 与 vue 别名保证单份 runtime；
// 这里统一再导出被测组件，测试文件按需引入
export { default as EvIcon } from '../src/components/icon/index.vue'
export { default as EvButton } from '../src/components/button/index.vue'
export { default as EvIconButton } from '../src/components/icon-button/index.vue'
export { default as EvTag } from '../src/components/tag/index.vue'
export { default as EvBadge } from '../src/components/badge/index.vue'
export { default as EvCard } from '../src/components/card/index.vue'
export { default as EvSection } from '../src/components/section/index.vue'
export { default as EvNavbar } from '../src/components/navbar/index.vue'
export { default as EvFooter } from '../src/components/footer/index.vue'
export { default as EvHero } from '../src/components/hero/index.vue'
export { default as EvSearchBox } from '../src/components/search-box/index.vue'
export { default as EvAiPromptBox } from '../src/components/ai-prompt-box/index.vue'
export { default as EvIconGrid } from '../src/components/icon-grid/index.vue'
export { default as EvFeatureGrid } from '../src/components/feature-grid/index.vue'
export { default as EvPricingCard } from '../src/components/pricing-card/index.vue'
export { default as EvFaq } from '../src/components/faq/index.vue'
export { default as EvAlert } from '../src/components/alert/index.vue'
export { default as EvCodeBlock } from '../src/components/code-block/index.vue'
export { default as EvKeycap } from '../src/components/keycap/index.vue'
export { default as EvStatistic } from '../src/components/statistic/index.vue'
export { default as EvThemeToggle } from '../src/components/theme-toggle/index.vue'
export { default as EvQuote } from '../src/components/quote/index.vue'
export { default as EvConfigProvider } from '../src/components/config-provider/index.vue'
export { default as EvTabs } from '../src/components/tabs/index.vue'
export { default as EvSwitch } from '../src/components/switch-comp/index.vue'
export { default as EvContainer } from '../src/components/container/index.vue'
export { default as EvAvatar } from '../src/components/avatar/index.vue'
export { default as EvAvatarGroup } from '../src/components/avatar/group.vue'
export { default as EvTimeline } from '../src/components/timeline/index.vue'
export { default as EvComparisonTable } from '../src/components/comparison-table/index.vue'
export { default as EvCta } from '../src/components/cta/index.vue'
export { default as EvNewsletter } from '../src/components/newsletter/index.vue'
export { default as EvLogoCloud } from '../src/components/logo-cloud/index.vue'
export { default as EvVideo } from '../src/components/video/index.vue'
export { default as EvAudio } from '../src/components/audio/index.vue'
export { default as EvContactForm } from '../src/components/contact-form/index.vue'
export { default as EvCarousel } from '../src/components/carousel/index.vue'
export { default as EvArticleCard } from '../src/components/article-card/index.vue'
export { default as EvProfileCard } from '../src/components/profile-card/index.vue'
export { default as EvMarquee } from '../src/components/marquee/index.vue'
export { default as EvInput } from '../src/components/input/index.vue'
export { default as EvTextarea } from '../src/components/textarea/index.vue'
export { default as EvSelect } from '../src/components/select/index.vue'
export { default as EvField } from '../src/components/field/index.vue'
export { default as EvScrollScene } from '../src/components/scroll-scene/index.vue'
export { default as EvBento } from '../src/components/bento/index.vue'
export { default as EvSlider } from '../src/components/slider/index.vue'
export { default as EvBorderBeam } from '../src/components/border-beam/index.vue'
export { default as EvExecCard } from '../src/components/exec-card/index.vue'
export { default as EvArticle } from '../src/components/article/index.vue'
export { default as EvImageWall } from '../src/components/image-wall/index.vue'
export { default as EvImagePreview } from '../src/components/image-preview/index.vue'
export { default as EvWaterfall } from '../src/components/waterfall/index.vue'
export { default as EvModal } from '../src/components/modal/index.vue'

// Components — 移动组件
export { default as EvPullRefresh } from '../src/components/pull-refresh/index.vue'
export { default as EvLoadMore } from '../src/components/load-more/index.vue'
export { default as EvActionSheet } from '../src/components/action-sheet/index.vue'
export { default as EvTabbar } from '../src/components/tabbar/index.vue'
export { default as EvTabbarItem } from '../src/components/tabbar/item.vue'
export { default as EvNavBar } from '../src/components/nav-bar/index.vue'

export { registerIcons, getIconByName, getIconNames, hasIcon } from '../src/components/icon/iconRegistry'
